export const Types = {
  GET_EMERGENCY_CONTACTS: 'GET_EMERGENCY_CONTACTS',
  GET_EMERGENCY_CONTACT: 'GET_EMERGENCY_CONTACT',
  ADD_EMERGENCY_CONTACT: 'ADD_EMERGENCY_CONTACT',
  REMOVE_EMERGENCY_CONTACT: 'REMOVE_EMERGENCY_CONTACT',
  UPDATE_EMERGENCY_CONTACT: 'UPDATE_EMERGENCY_CONTACT',
}
